apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Internal-only, not exposed publicly
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
